name: Bash-checks
on:
  pull_request:
    paths:
      - 'bash/*'

jobs:
  bash-checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        run: git clone https://github.com/kward/shunit2.git shunit2; export PATH="$(pwd)/shunit2:${PATH}"; cmake . -Bout
      - name: lint
        run: make -Cout bash-lint
      - name: test
        run: make -Cout bash-test
